Enable: Participate as team for hackathons
fossunited/fossunited pull request #103
Opened 2023-12-21 10:25 UTC by RiyaMathew-11

The event admin/creator of a hackathon can mandate whether it should be a team event on not. 

This is a short PR that mainly handles mandating a team option for hackathons as mentioned in #69 

- It auto-assigns a participant who creates a team as team lead
- Provides a status check for the team lead.

2023-12-23 18:49 UTC, harshtandiya commented
Is this PR ready for review? It is still in draft state

2023-12-23 18:54 UTC, harshtandiya requested changes

2023-12-23 18:54 UTC, harshtandiya commented on fossunited/hackathon/doctype/foss_hackathon_teams/foss_hackathon_teams.py
> +        print(participant_hash)
test print I guess? Let's remove it

2023-12-23 18:54 UTC, harshtandiya commented on fossunited/hackathon/doctype/foss_hackathon_teams/foss_hackathon_teams.py
> +        participant_hash = frappe.db.get_value(
Let's just name it participant

2023-12-28 08:05 UTC, RiyaMathew-11 commented on fossunited/hackathon/doctype/foss_hackathon_teams/foss_hackathon_teams.py
> +        participant_hash = frappe.db.get_value(
Done

2023-12-28 09:36 UTC, harshtandiya approved these changes

2023-12-28 10:06 UTC, merged