Homepage
fossunited/fossunited pull request #112
Opened 2024-01-24 05:18 UTC by RiyaMathew-11

## What type of PR is this? (check all applicable)
- [x] 🍕Feature
- [ ] ⚙️Chore
- [ ] 🐛Bug Fix
- [ ] 🎨Style
- [ ] 🧑‍💻Refactor
- [ ] 📕Documentation
- [ ] 🏎️Optimization

## Description
- This PR completes the homepage of the new platform.
- The sections included are hero, about, programs, featured events, team, industry partnership and contact.

## Related Issues & Docs
 - Closes #102 

## Checklist
- [ ] I have read the [contribution guidelines]("./docs/CONTRIBUTING.md").
- [ ] I have tested these changes locally.
- [ ] I have updated the documentation (If applicable).
- [ ] The code follows the project's coding standards.
- [ ] I have added/updated tests, if applicable.

## Screenshots/GIFs/Screen Recordings (if applicable)

## [optional] What gif best describes this PR or how it makes you feel?

2024-02-01 18:29 UTC, harshtandiya requested changes

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/doctype/foss_united_team/foss_united_team.json
> +   "fetch_from": ".profile_photo",
fetch from where?

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/doctype/foss_united_team/foss_united_team.json
> +   "fetch_from": ".bio",
same here

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/doctype/foss_united_team/foss_united_team.json
> + ],
Add a permission for ALL to atleast Read/Select it

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/doctype/industry_partners/industry_partners.json
> +  "is_current",
`is_current_partner` would be better naming imo

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/doctype/industry_partners/industry_partners.json
> + ],
Permission for ALL to Read it

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/web_template/foss_footer/foss_footer.html
> +
Why not just give the `color` attribute in footer-container rather than explicitly doing for each one.

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/web_template/foss_footer/foss_footer.html
> +                     {% endfor %}
What if the item doesn't have a parent label but has a URL? I think the Label will be printed but the URL will not be there. Please fix

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/web_template/foss_footer/foss_footer.html
> +                    {% set website_settings = frappe.get_doc("Website Settings")%}
Not needed. We already have context for this

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___contact/home_page___contact.html
> +        padding: 0rem 14rem 0rem 14rem;
Rather than giving a padding here, maybe use a .container class inside the child div

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___contact/home_page___contact.html
> +        .mobile-only{
maybe try a better class name

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___contact/home_page___contact.html
> +                <img src="" alt="">
Why img tag here

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___contact/home_page___contact.html
> +                Join our <a href="https://t.me/fossunited">Telegram Community</a>. <br/><br/>
Add telegram link from server side (add a field for it in template)

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___contact/home_page___contact.html
> +<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@2.46.0/tabler-icons.min.css">
The web page is not using any Tabler Icon, so I think this can be removed

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___events/home_page___events.html
> +    }
Try using .container class from bootstrap wherever possible

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___events/home_page___events.html
> +        width: 100%;
A lot of these styles are not needed. They are coming from Figma, but some of them are redundant / unnecessary.

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___events/home_page___events.html
> +        width: 100%;
There's a lot of that happening in a lot of other classes. Let's clean the code in the coming PRs. This is not required change, but something that should be done

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___events/home_page___events.html
> +                    <p class="flagship-card-cta">More >></p>
You can use Tabler icon here rather than >>

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___events/home_page___events.html
> +                </a>
Why not have these as fields in template. The content would be easier to change that way.

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___events/home_page___events.html
> +            {% set events = frappe.get_all("FOSS Chapter Events", fields=["event_name", "must_attend", "event_location", "map_link", "event_start_date"], filters={"status": "Approved"}, page_length=3
Will page_length 3 will get only 3 entries? If so, that is too low in my opinion. We should atleast show 6 if the grid is a 3 column

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___hero_and_about_section/home_page___hero_and_about_section.html
> +        padding: 0rem 14rem 0rem 14rem;
use .container in child div

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___industry_partnership/home_page___industry_partnership.html
> +            </div>
Why the wrapper div, also let's give a class or ID to the img

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___industry_partnership/home_page___industry_partnership.html
> +<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@2.46.0/tabler-icons.min.css">
Not used in this page, this can be removed

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___programs_section/home_page___programs_section.html
> +                {% set logo = values['program_' + index|string + '_logo'] %}
Where is `values` coming from

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___events/home_page___events.html
> +                <a class="flagship-event-card" href="">
No href?

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___events/home_page___events.html
> +                <a class="flagship-event-card" href="">
No href (2)

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___programs_section/home_page___programs_section.html
> +                        <a class="program-card" href="">
no href (3)

2024-02-01 18:29 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___team/home_page___team.html
> +                    {% if employee.is_active == 1 %}
Just add this as a filter in get_all, and remove this line

2024-02-02 07:03 UTC, RiyaMathew-11 commented on fossunited/fossunited/doctype/foss_united_team/foss_united_team.json
> +   "fetch_from": ".profile_photo",
It should fetch from FOSS User Profile - the name, username and profile photo. Have updated the same.

2024-02-03 09:12 UTC, harshtandiya requested changes

2024-02-03 09:12 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___events/home_page___events.html
> +                <a class="flagship-event-card" href="">
There is still no href for this? Is this supposed to be empty?

2024-02-03 09:12 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___contact/home_page___contact.html
> +                Join our <a href="https://t.me/fossunited">Telegram Community</a>. <br/><br/>
Why not take the telegram link as a variable value from the template fields

2024-02-03 09:12 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___events/home_page___events.html
> +            {% set events = frappe.get_all("FOSS Chapter Events", fields=["event_name", "must_attend", "event_location", "map_link", "event_start_date"], filters={"status": "Approved"}, page_length=3
Please clarify @RiyaMathew-11

2024-02-03 09:12 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___events/home_page___events.html
> +                        <a href="" class="event-details">
Empty href again. I think you should get the route value of the events and place them here

2024-02-03 09:12 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___programs_section/home_page___programs_section.html
> +                        <a class="program-card" href="">
Again no href values

2024-02-03 16:31 UTC, harshtandiya approved these changes

2024-02-03 17:14 UTC, merged