Ticket redesign
fossunited/fossunited pull request #167
Opened 2024-03-03 19:34 UTC by Mangeshrex

## What type of PR is this? (check all applicable)
- [ ] 🍕Feature
- [ ] ⚙️Chore
- [ ] 🐛Bug Fix
- [x] 🎨Style
- [x] 🧑‍💻Refactor
- [ ] 📕Documentation
- [ ] 🏎️Optimization

## Description
This PR is to apply the redesigns of the book conference ticket page. 

## Related Issues & Docs

## Checklist
- [x] I have read the [contribution guidelines]("./docs/CONTRIBUTING.md").
- [x] I have tested these changes locally.
- [x] I have updated the documentation (If applicable).
- [x] The code follows the project's coding standards.
- [x] I have added/updated tests, if applicable.

## Screenshots/GIFs/Screen Recordings (if applicable)
![image](https://github.com/fossunited/fossunited/assets/82205152/050546a1-2fb1-46d4-abb2-a3e77433ae5f)

## Additional context

## [optional] What gif best describes this PR or how it makes you feel?

2024-03-06 20:27 UTC, harshtandiya approved these changes

2024-03-06 20:28 UTC, harshtandiya requested changes

2024-03-06 20:28 UTC, harshtandiya commented on fossunited/chapters/doctype/foss_chapter_events/foss_chapter_events.py
> +            navbar_items.remove("rsvp")
This can be an OR case

2024-03-06 20:41 UTC, Mangeshrex commented on fossunited/chapters/doctype/foss_chapter_events/foss_chapter_events.py
> +            navbar_items.remove("rsvp")
fixed this

2024-03-07 05:56 UTC, harshtandiya approved these changes

2024-03-07 07:23 UTC, merged