A quick fix PR
fossunited/fossunited pull request #203
Opened 2024-03-20 16:01 UTC by RiyaMathew-11

## What type of PR is this? (check all applicable)

- [x] ⚙️Chore
- [x] 🐛Bug Fix

## Description
This is a small PR that handles 2 things: 

1. A bug fix: The current home page shows redundancy in content for goal text.
2. Chore: Added fields to showcase more programs in homepage - currently had only three - made it 6 for now. 

   -  Six seemed the ideal number for home page, can add more in future or redirect to a separate page for programs listing.

## Checklist
- [ ] I have read the [contribution guidelines]("./docs/CONTRIBUTING.md").
- [ ] I have tested these changes locally.
- [ ] I have updated the documentation (If applicable).
- [ ] The code follows the project's coding standards.
- [ ] I have added/updated tests, if applicable.

## Screenshots/GIFs/Screen Recordings (if applicable)

<img width="1311" alt="Screenshot 2024-03-20 at 9 30 31 PM" src="https://github.com/fossunited/fossunited/assets/60656677/0a3723af-8252-4ed5-b787-3b6521580c96">

<img width="1311" alt="Screenshot 2024-03-20 at 9 30 21 PM" src="https://github.com/fossunited/fossunited/assets/60656677/d4172716-2490-4021-94c4-b183b214149e">

2024-03-27 06:23 UTC, harshtandiya requested changes

2024-03-27 06:23 UTC, harshtandiya commented on fossunited/public/css/custom.css
> -    padding: 0.625rem 0.75rem;
Why? These are the dimensions which are in design. Please attach a screenshot for before and after of this.

2024-03-27 06:23 UTC, harshtandiya commented on fossunited/fossunited/web_template/home_page___events/home_page___events.html
> -    </div>
Why was this removed?

2024-03-28 17:35 UTC, RiyaMathew-11 commented on fossunited/public/css/custom.css
> -    padding: 0.625rem 0.75rem;
I felt the buttons were a bit constricted in the screen - 0.75:1 gives it a 3:4 proportion - which when I checked gives a bit of expansion and keeps proportion but does not change much of size.

Before Change:  

<img width="268" alt="Screenshot 2024-03-27 at 7 56 22 PM" src="https://github.com/fossunited/fossunited/assets/60656677/c11e2528-170b-4d5c-a12d-c2fd26a119ac">

After change: 

<img width="268" alt="Screenshot 2024-03-27 at 7 57 07 PM" src="https://github.com/fossunited/fossunited/assets/60656677/10f87d2f-26bc-4ad1-969c-6ef5efc4571b">

2024-03-28 17:35 UTC, RiyaMathew-11 commented on fossunited/fossunited/web_template/home_page___events/home_page___events.html
> -    </div>
There is an [upcoming events template](https://github.com/fossunited/fossunited/tree/develop/fossunited/fossunited/web_template/foss_events___upcoming_events_section) that is used in the events page. 

We could reuse the same in home page - having both of them is redundant. The alignment issue wrt container in this template - I've fixed it in a commit.

2024-03-28 18:16 UTC, harshtandiya approved these changes

2024-03-28 18:16 UTC, merged