feat: rsvp count & rsvp email confirmation notifications
fossunited/fossunited pull request #29
Opened 2023-09-15 08:46 UTC by harshtandiya

#23 

- Event RSVP added a `max_rsvp_count` (default = 100) and `rsvp_count` field.
- When RSVPs are registered, it increases the `rsvp_count` of the event.
- When `rsvp_count >= max_rsvp_count`, the RSVP form will be unpublished.
- Emails will be sent to the user when they RSVP for an event.

2023-09-16 13:46 UTC, NagariaHussain requested changes

2023-09-16 13:46 UTC, NagariaHussain commented on fossunited/chapters/doctype/foss_event_rsvp/foss_event_rsvp.json
> +   "label": "RSVP Count"
Shouldn't this be `Int`s?

2023-09-16 13:46 UTC, NagariaHussain commented on fossunited/fossunited/notification/rsvp_confirmation_email/rsvp_confirmation_email.md
> +<h1>Thank you for RSVPing</h1>
HTML in .md file? Maybe you wanted to have a Jinja template (inside templates folder of the app)

2023-09-20 06:11 UTC, harshtandiya commented
@NagariaHussain Can you review and approve please

2023-09-20 06:21 UTC, NagariaHussain approved these changes

2023-09-21 14:05 UTC, merged