feat: cfp added
fossunited/fossunited pull request #30
Opened 2023-09-17 11:30 UTC by harshtandiya

2023-09-22 08:30 UTC, NagariaHussain requested changes

2023-09-22 08:30 UTC, NagariaHussain commented on fossunited/fossunited/doctype/foss_event_cfp/foss_event_cfp.py
> +	def self_route(self):
```suggestion
	def set_route(self):
```

😅

2023-09-22 09:05 UTC, harshtandiya commented on fossunited/fossunited/doctype/foss_event_cfp/foss_event_cfp.py
> +	def self_route(self):
🫣 correcting

2023-09-24 05:41 UTC, NagariaHussain approved these changes

2023-09-24 19:00 UTC, merged