feat: CFP submissions added w review
fossunited/fossunited pull request #41
Opened 2023-10-21 22:11 UTC by harshtandiya

CFP Portals are live now, with the addition of an inhouse ability to provide reviews to the CFPs.
More development on the UX for the reviewers in v2 by taking real world usage feedback.

Features Added:

- [x] Ability to "Like" the CFP
- [x] Ability to Comment on the CFP
- [x] UI for CFP
- [x] Ability to change status
- [x] Ability for the reviewers to add reviews and cast their votes
- [x] Option to make proposals anonymous

## If part of the Chapter Team
![image](https://github.com/fossunited/fossunited/assets/73123690/6567ef36-9052-42d4-8bb6-d6814c01e340)
![image](https://github.com/fossunited/fossunited/assets/73123690/d8fc04ec-b959-4cf1-9d05-af4dd4c249e0)
![image](https://github.com/fossunited/fossunited/assets/73123690/5c3dc16c-80fa-4d6d-8fd0-b109c4a109c1)
![image](https://github.com/fossunited/fossunited/assets/73123690/b259c9c7-0fd2-440b-8132-0f63385f3885)
![image](https://github.com/fossunited/fossunited/assets/73123690/988a64fb-bf22-4234-9a7b-5244bf870935)

Everything for the reviewers remains the same, except the ability to change status. This power lies only with the chapter members.

## Guest View
![image](https://github.com/fossunited/fossunited/assets/73123690/edb5ab15-714d-4e90-b26d-ffb645e981ca)

2023-10-22 06:37 UTC, NagariaHussain requested changes
Naming booleans as verbs make them more readable. For example:

```
if anonymise_proposals:
```

has better readability compared to:

```
if anonymous_proposals:
```


One of the good clean code principles I think...

Similarly one more example: `is_published` is more readable than `published`.

2023-10-22 06:55 UTC, NagariaHussain requested changes
Focused more on general code quality... Good going 👍

2023-10-22 06:55 UTC, NagariaHussain commented on fossunited/fossunited/doctype/foss_event_cfp_reviews/foss_event_cfp_reviews.json
> +   "label": "Can Approve?",
"Who" can approve?

2023-10-22 06:55 UTC, NagariaHussain commented on fossunited/fossunited/doctype/foss_event_cfp_submission/templates/foss_event_cfp_submission.html
> +        {% if doc.first_talk == "Yes" %}
Should be a Boolean? 

```suggestion
        {% if doc.is_first_talk %}
```

Again, readability. Look for Uncle bob btw @harshtandiya 😀

2023-10-22 06:55 UTC, NagariaHussain commented on fossunited/fossunited/doctype/foss_event_cfp_submission/templates/foss_event_cfp_submission.html
> +                {{ _("0") }}
```suggestion
                0
```

Why translate a number, static too

2023-10-22 06:55 UTC, NagariaHussain commented on fossunited/fossunited/doctype/foss_event_cfp_submission/templates/foss_event_cfp_submission.html
> +                {% for option in ['Open', 'Approved', 'Rejected'] %}
```suggestion
                {% for option in ('Open', 'Approved', 'Rejected') %}
```

PerForMaNce...

2023-10-22 06:55 UTC, NagariaHussain commented on fossunited/fossunited/doctype/foss_event_cfp_submission/templates/foss_event_cfp_submission.html
> +        {% set style = ({
```suggestion
        {% set style_map = ({
```

2023-10-22 06:55 UTC, NagariaHussain commented on fossunited/fossunited/doctype/foss_event_cfp_submission/templates/foss_event_cfp_submission.html
> +{% macro BreadCrumb(route) %}
Sticking to snake case is better I think:

```suggestion
{% macro breadcrumbs(route) %}
```

Plural because generally at least 2.

2023-10-22 06:55 UTC, NagariaHussain commented on fossunited/fossunited/doctype/foss_event_cfp_submission/templates/foss_event_cfp_submission.html
> +{% macro RenderComment(comment) %}
```suggestion
{% macro render_comment(comment) %}
```

2023-10-22 06:55 UTC, NagariaHussain commented on fossunited/fossunited/utils.py
> +	print(is_team_member)
Debug print?

2023-10-22 06:55 UTC, NagariaHussain commented on fossunited/fossunited/utils.py
> +		print(f"Error decoding JSON: {e}")
Maybe do frappe.throw, instead of silently ignoring...

2023-10-22 06:55 UTC, NagariaHussain commented on fossunited/fossunited/utils.py
> +	if anonymous_proposals == 0:
```suggestion
	if not anonymise_proposals:
```

2023-10-22 06:55 UTC, NagariaHussain commented on fossunited/fossunited/utils.py
> +	print(event)
Debug?

2023-10-22 12:39 UTC, harshtandiya commented on fossunited/fossunited/utils.py
> +	print(is_team_member)
damn lol

2023-10-23 11:23 UTC, NagariaHussain requested changes

2023-10-23 11:23 UTC, NagariaHussain commented on fossunited/fossunited/utils.py
> +	if anonymise_proposals == 0:
```suggestion
	if not anonymise_proposals:
```

2023-10-23 12:49 UTC, NagariaHussain approved these changes

2023-10-23 12:52 UTC, merged