Fixes Unique check for event creation bug
fossunited/fossunited pull request #700
Opened 2024-11-18 20:18 UTC by vasujain275

## What type of PR is this? (check all applicable)

- [ ] 🍕Feature
- [ ] ⚙️Chore
- [x] 🐛Bug Fix
- [ ] 🎨Style
- [ ] 🧑‍💻Refactor
- [ ] 📕Documentation
- [ ] 🏎️Optimization

## Description

Unchecked the Unique flag on `Event Permalink` from `FOSS Chapter Event` Doctype. Now, two different chapters can have same slug in event permalink. Also modified test case to validate the same.

## Related Issues & Docs

closes #690 

## Checklist

- [x] I have read the [contribution guidelines]("./docs/CONTRIBUTING.md").
- [x] I have tested these changes locally.
- [ ] I have updated the documentation (If applicable).
- [x] The code follows the project's coding standards.
- [x] I have added/updated tests, if applicable.

## Screenshots/GIFs/Screen Recordings (if applicable)

N/A

## Additional context

N/A

2024-11-18 20:40 UTC, vasujain275 commented
Sorry for the linting/formatting errors, reinstalled the local bench and forgot to install pre-commit hook

2024-11-19 03:22 UTC, rahulporuri commented
i sincerely apologize but i have a fundamental question about this approach - https://github.com/fossunited/fossunited/issues/690#issuecomment-2484626162

2024-11-19 03:38 UTC, harshtandiya commented
Looks like your precommit is not set up correctly @vasujain275

2024-11-19 05:18 UTC, vasujain275 commented
@harshtandiya my bad, now pre commit is working on my local setup correctly

2024-11-19 18:16 UTC, harshtandiya requested changes

2024-11-19 18:16 UTC, harshtandiya commented on fossunited/chapters/doctype/foss_chapter_event/test_foss_chapter_event.py
> +            )
Alignment isssues? Dont think this is supposed to be here. 

I do like the idea of having central functions for creating chapter and event. However, I do not think we should do it here. We can create a `utils.py` file in the test directory inside fossunited. In that file we can write these functions and then import them to other tests to use.

2024-11-19 18:16 UTC, harshtandiya commented on fossunited/chapters/doctype/foss_chapter_event/test_foss_chapter_event.py
> +                    "state": "Kerala",
same as above

2024-11-19 18:16 UTC, harshtandiya commented on fossunited/chapters/doctype/foss_chapter_event/foss_chapter_event.js
> +// });
Let's unstage this file

2024-11-19 18:16 UTC, harshtandiya commented on fossunited/chapters/doctype/foss_chapter_event/foss_chapter_event.json
> + "actions": [],
`yarn format` will fix this file's formatting

2024-11-20 08:00 UTC, harshtandiya approved these changes
great job!

2024-11-20 12:48 UTC, merged