Newsletter Web Page and Base Features
fossunited/fossunited pull request #96
Opened 2023-12-09 07:53 UTC by Mangeshrex

This is a base PR for the FOSS United Newsletter on new Platform. PR Includes: 
- Newsletter UI (subject to change) 
- Email Group for FOSS United Newsletters
- Subscribe to newsletter feature with frappe.call
- Temporary success page (subject to change - mostly in the next PR)

Demonstration: 
https://github.com/fossunited/fossunited/assets/82205152/c582a20d-765b-4c06-b997-7b6b67ab49ef

2023-12-10 17:08 UTC, harshtandiya commented
Attach screenshots. The demo is not working

2023-12-10 17:52 UTC, Mangeshrex commented
![image](https://github.com/fossunited/fossunited/assets/82205152/a1e33581-23cc-4b2a-9e3b-6457cdfbd080)

![image](https://github.com/fossunited/fossunited/assets/82205152/6ea0c817-7e43-49b6-9e8a-5335dec62507)

2023-12-12 14:04 UTC, RiyaMathew-11 commented
Looks clean. Maybe instead of the dummy text in the email address field, keep a dummy placeholder email - maybe username@example.com. 

We might need to merge design styles too.

2023-12-12 14:06 UTC, RiyaMathew-11 reviewed
Looks clean. Maybe instead of the dummy text in the email address field, keep a dummy placeholder email - maybe [username@example.com](mailto:username@example.com).

We might need to merge design styles too.

2023-12-13 06:37 UTC, Mangeshrex commented
Sure, I'll push an update.

2023-12-13 06:42 UTC, harshtandiya commented
Can you put a screenshot of success page too

2023-12-13 06:43 UTC, Mangeshrex commented
![image](https://github.com/fossunited/fossunited/assets/82205152/5e4d99c2-4c63-461f-a393-f4f6a328bc6d)

2023-12-13 06:50 UTC, harshtandiya commented
Make it a bit better with a green tick maybe

2023-12-13 14:07 UTC, Mangeshrex commented
![Cheese_Wed-13Dec23_18 36](https://github.com/fossunited/fossunited/assets/82205152/f39eb3cf-b9a0-46b8-a3f3-4fbf77835d60)

2023-12-13 17:35 UTC, harshtandiya requested changes

2023-12-13 17:35 UTC, harshtandiya commented on fossunited/www/newsletter/index.js
> +  var emailInput = document.getElementById("email").value;
use let instead of var as much as possible

2023-12-13 17:35 UTC, harshtandiya commented on fossunited/www/newsletter/index.js
> +  }
let's replace var with let

2023-12-13 17:35 UTC, harshtandiya commented on fossunited/www/newsletter/index.html
> +        {% endfor %}
Kind of redundant. I suggest replacing the `<li>` with `<a>` and remove line 41.

2023-12-13 17:35 UTC, harshtandiya commented on fossunited/www/newsletter/index.html
> +        </div>
being nitpicky but the outer div is not needed I guess

2023-12-13 17:54 UTC, harshtandiya approved these changes

2023-12-13 17:55 UTC, merged